#
# Torizon OTA
#  This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  
# Version: 2.0-Beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'TorizonPlatformAPI' -name 'TorizonPlatformAPITorizonPlatformAPIDevicesApi' {
    Context 'Invoke-TorizonPlatformAPIDeleteDevicesDeviceuuid' {
        It 'Test Invoke-TorizonPlatformAPIDeleteDevicesDeviceuuid' {
            #$TestResult = Invoke-TorizonPlatformAPIDeleteDevicesDeviceuuid -DeviceUuid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIDevices' {
        It 'Test Get-TorizonPlatformAPIDevices' {
            #$TestResult = Get-TorizonPlatformAPIDevices -Offset "TEST_VALUE" -Limit "TEST_VALUE" -DeviceUuid "TEST_VALUE" -NameContains "TEST_VALUE" -SortBy "TEST_VALUE" -SortDirection "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIDevicesDeviceuuid' {
        It 'Test Get-TorizonPlatformAPIDevicesDeviceuuid' {
            #$TestResult = Get-TorizonPlatformAPIDevicesDeviceuuid -DeviceUuid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIDevicesNameDeviceuuid' {
        It 'Test Get-TorizonPlatformAPIDevicesNameDeviceuuid' {
            #$TestResult = Get-TorizonPlatformAPIDevicesNameDeviceuuid -DeviceUuid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIDevicesNetwork' {
        It 'Test Get-TorizonPlatformAPIDevicesNetwork' {
            #$TestResult = Get-TorizonPlatformAPIDevicesNetwork -Offset "TEST_VALUE" -Limit "TEST_VALUE" -DeviceUuid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIDevicesNetworkDeviceuuid' {
        It 'Test Get-TorizonPlatformAPIDevicesNetworkDeviceuuid' {
            #$TestResult = Get-TorizonPlatformAPIDevicesNetworkDeviceuuid -DeviceUuid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIDevicesNotesDeviceuuid' {
        It 'Test Get-TorizonPlatformAPIDevicesNotesDeviceuuid' {
            #$TestResult = Get-TorizonPlatformAPIDevicesNotesDeviceuuid -DeviceUuid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIDevicesPackages' {
        It 'Test Get-TorizonPlatformAPIDevicesPackages' {
            #$TestResult = Get-TorizonPlatformAPIDevicesPackages -Offset "TEST_VALUE" -Limit "TEST_VALUE" -DeviceUuid "TEST_VALUE" -NameContains "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIDevicesPackagesDeviceuuid' {
        It 'Test Get-TorizonPlatformAPIDevicesPackagesDeviceuuid' {
            #$TestResult = Get-TorizonPlatformAPIDevicesPackagesDeviceuuid -DeviceUuid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIDevicesToken' {
        It 'Test Get-TorizonPlatformAPIDevicesToken' {
            #$TestResult = Get-TorizonPlatformAPIDevicesToken
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIDevicesUptaneDeviceuuidAssignment' {
        It 'Test Get-TorizonPlatformAPIDevicesUptaneDeviceuuidAssignment' {
            #$TestResult = Get-TorizonPlatformAPIDevicesUptaneDeviceuuidAssignment -DeviceUuid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIDevicesUptaneDeviceuuidComponents' {
        It 'Test Get-TorizonPlatformAPIDevicesUptaneDeviceuuidComponents' {
            #$TestResult = Get-TorizonPlatformAPIDevicesUptaneDeviceuuidComponents -DeviceUuid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Submit-TorizonPlatformAPIDevices' {
        It 'Test Submit-TorizonPlatformAPIDevices' {
            #$TestResult = Submit-TorizonPlatformAPIDevices -DeviceCreateReq "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Send-TorizonPlatformAPIDevicesNameDeviceuuid' {
        It 'Test Send-TorizonPlatformAPIDevicesNameDeviceuuid' {
            #$TestResult = Send-TorizonPlatformAPIDevicesNameDeviceuuid -DeviceUuid "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Send-TorizonPlatformAPIDevicesNotesDeviceuuid' {
        It 'Test Send-TorizonPlatformAPIDevicesNotesDeviceuuid' {
            #$TestResult = Send-TorizonPlatformAPIDevicesNotesDeviceuuid -DeviceUuid "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
