#
# Torizon OTA
#  This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  
# Version: 2.0-Beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'TorizonPlatformAPI' -name 'TorizonPlatformAPITorizonPlatformAPIPackagesApi' {
    Context 'Invoke-TorizonPlatformAPIDeletePackagesPackageid' {
        It 'Test Invoke-TorizonPlatformAPIDeletePackagesPackageid' {
            #$TestResult = Invoke-TorizonPlatformAPIDeletePackagesPackageid -PackageId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIPackages' {
        It 'Test Get-TorizonPlatformAPIPackages' {
            #$TestResult = Get-TorizonPlatformAPIPackages -Offset "TEST_VALUE" -Limit "TEST_VALUE" -IdContains "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIPackagesExternal' {
        It 'Test Get-TorizonPlatformAPIPackagesExternal' {
            #$TestResult = Get-TorizonPlatformAPIPackagesExternal -Offset "TEST_VALUE" -Limit "TEST_VALUE" -IdContains "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIPackagesExternalInfo' {
        It 'Test Get-TorizonPlatformAPIPackagesExternalInfo' {
            #$TestResult = Get-TorizonPlatformAPIPackagesExternalInfo
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIPackagesExternalRefreshSourceFileName' {
        It 'Test Get-TorizonPlatformAPIPackagesExternalRefreshSourceFileName' {
            #$TestResult = Get-TorizonPlatformAPIPackagesExternalRefreshSourceFileName -SourceFileName "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-TorizonPlatformAPIPatchPackagesPackageid' {
        It 'Test Invoke-TorizonPlatformAPIPatchPackagesPackageid' {
            #$TestResult = Invoke-TorizonPlatformAPIPatchPackagesPackageid -PackageId "TEST_VALUE" -EditPackage "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Submit-TorizonPlatformAPIPackages' {
        It 'Test Submit-TorizonPlatformAPIPackages' {
            #$TestResult = Submit-TorizonPlatformAPIPackages -Name "TEST_VALUE" -Version "TEST_VALUE" -TargetFormat "TEST_VALUE" -ContentLength "TEST_VALUE" -Body "TEST_VALUE" -HardwareId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
