#
# Torizon OTA
#  This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  
# Version: 2.0-Beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'TorizonPlatformAPI' -name 'TorizonPlatformAPITorizonPlatformAPIUpdatesApi' {
    Context 'Get-TorizonPlatformAPILockboxDetails' {
        It 'Test Get-TorizonPlatformAPILockboxDetails' {
            #$TestResult = Get-TorizonPlatformAPILockboxDetails
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPILockboxes' {
        It 'Test Get-TorizonPlatformAPILockboxes' {
            #$TestResult = Get-TorizonPlatformAPILockboxes
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPILockboxesLockboxName' {
        It 'Test Get-TorizonPlatformAPILockboxesLockboxName' {
            #$TestResult = Get-TorizonPlatformAPILockboxesLockboxName -LockboxName "TEST_VALUE" -Version "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-TorizonPlatformAPIPatchUpdates' {
        It 'Test Invoke-TorizonPlatformAPIPatchUpdates' {
            #$TestResult = Invoke-TorizonPlatformAPIPatchUpdates -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Submit-TorizonPlatformAPILockboxesLockboxName' {
        It 'Test Submit-TorizonPlatformAPILockboxesLockboxName' {
            #$TestResult = Submit-TorizonPlatformAPILockboxesLockboxName -LockboxName "TEST_VALUE" -CreateLockboxRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Submit-TorizonPlatformAPIUpdates' {
        It 'Test Submit-TorizonPlatformAPIUpdates' {
            #$TestResult = Submit-TorizonPlatformAPIUpdates -UpdateRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
