#
# Torizon OTA
#  This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  
# Version: 2.0-Beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'TorizonPlatformAPI' -name 'TorizonPlatformAPITorizonPlatformAPIFleetsApi' {
    Context 'Invoke-TorizonPlatformAPIDeleteFleetsFleetid' {
        It 'Test Invoke-TorizonPlatformAPIDeleteFleetsFleetid' {
            #$TestResult = Invoke-TorizonPlatformAPIDeleteFleetsFleetid -FleetId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-TorizonPlatformAPIDeleteFleetsFleetidDevices' {
        It 'Test Invoke-TorizonPlatformAPIDeleteFleetsFleetidDevices' {
            #$TestResult = Invoke-TorizonPlatformAPIDeleteFleetsFleetidDevices -FleetId "TEST_VALUE" -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIFleets' {
        It 'Test Get-TorizonPlatformAPIFleets' {
            #$TestResult = Get-TorizonPlatformAPIFleets -Offset "TEST_VALUE" -Limit "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TorizonPlatformAPIFleetsFleetidDevices' {
        It 'Test Get-TorizonPlatformAPIFleetsFleetidDevices' {
            #$TestResult = Get-TorizonPlatformAPIFleetsFleetidDevices -FleetId "TEST_VALUE" -Offset "TEST_VALUE" -Limit "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Submit-TorizonPlatformAPIFleets' {
        It 'Test Submit-TorizonPlatformAPIFleets' {
            #$TestResult = Submit-TorizonPlatformAPIFleets -CreateFleet "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Submit-TorizonPlatformAPIFleetsFleetidDevices' {
        It 'Test Submit-TorizonPlatformAPIFleetsFleetidDevices' {
            #$TestResult = Submit-TorizonPlatformAPIFleetsFleetidDevices -FleetId "TEST_VALUE" -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
