#
# Torizon OTA
#  This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  
# Version: 2.0-Beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Keyid
No description available.
.PARAMETER Sig
No description available.
.PARAMETER Method
No description available.
.OUTPUTS

ClientSignature<PSCustomObject>
#>

function Initialize-TorizonPlatformAPIClientSignature {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Keyid},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Sig},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("rsassa-pss-sha256", "ed25519", "ecPrime256v1")]
        [PSCustomObject]
        ${Method}
    )

    Process {
        'Creating PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIClientSignature' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Keyid) {
            throw "invalid value for 'Keyid', 'Keyid' cannot be null."
        }

        if ($null -eq $Sig) {
            throw "invalid value for 'Sig', 'Sig' cannot be null."
        }

        if ($null -eq $Method) {
            throw "invalid value for 'Method', 'Method' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "keyid" = ${Keyid}
            "sig" = ${Sig}
            "method" = ${Method}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClientSignature<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClientSignature<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClientSignature<PSCustomObject>
#>
function ConvertFrom-TorizonPlatformAPIJsonToClientSignature {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIClientSignature' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TorizonPlatformAPIClientSignature
        $AllProperties = ("keyid", "sig", "method")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'keyid' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "keyid"))) {
            throw "Error! JSON cannot be serialized due to the required property 'keyid' missing."
        } else {
            $Keyid = $JsonParameters.PSobject.Properties["keyid"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sig"))) {
            throw "Error! JSON cannot be serialized due to the required property 'sig' missing."
        } else {
            $Sig = $JsonParameters.PSobject.Properties["sig"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "method"))) {
            throw "Error! JSON cannot be serialized due to the required property 'method' missing."
        } else {
            $Method = $JsonParameters.PSobject.Properties["method"].value
        }

        $PSO = [PSCustomObject]@{
            "keyid" = ${Keyid}
            "sig" = ${Sig}
            "method" = ${Method}
        }

        return $PSO
    }

}

