#
# Torizon OTA
#  This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  
# Version: 2.0-Beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Expression
No description available.
.PARAMETER FleetType
No description available.
.PARAMETER Name
No description available.
.OUTPUTS

CreateFleet<PSCustomObject>
#>

function Initialize-TorizonPlatformAPICreateFleet {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Expression},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("static", "dynamic")]
        [PSCustomObject]
        ${FleetType},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name}
    )

    Process {
        'Creating PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPICreateFleet' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $FleetType) {
            throw "invalid value for 'FleetType', 'FleetType' cannot be null."
        }

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "expression" = ${Expression}
            "fleetType" = ${FleetType}
            "name" = ${Name}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CreateFleet<PSCustomObject>

.DESCRIPTION

Convert from JSON to CreateFleet<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CreateFleet<PSCustomObject>
#>
function ConvertFrom-TorizonPlatformAPIJsonToCreateFleet {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPICreateFleet' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TorizonPlatformAPICreateFleet
        $AllProperties = ("expression", "fleetType", "name")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'fleetType' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "fleetType"))) {
            throw "Error! JSON cannot be serialized due to the required property 'fleetType' missing."
        } else {
            $FleetType = $JsonParameters.PSobject.Properties["fleetType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "expression"))) { #optional property not found
            $Expression = $null
        } else {
            $Expression = $JsonParameters.PSobject.Properties["expression"].value
        }

        $PSO = [PSCustomObject]@{
            "expression" = ${Expression}
            "fleetType" = ${FleetType}
            "name" = ${Name}
        }

        return $PSO
    }

}

