#
# Torizon OTA
#  This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  
# Version: 2.0-Beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Size
No description available.
.PARAMETER Filepath
No description available.
.PARAMETER Hash
No description available.
.OUTPUTS

EcuInfoImage<PSCustomObject>
#>

function Initialize-TorizonPlatformAPIEcuInfoImage {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Int64]
        ${Size},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Filepath},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Hash}
    )

    Process {
        'Creating PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIEcuInfoImage' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Size) {
            throw "invalid value for 'Size', 'Size' cannot be null."
        }

        if ($null -eq $Filepath) {
            throw "invalid value for 'Filepath', 'Filepath' cannot be null."
        }

        if ($null -eq $Hash) {
            throw "invalid value for 'Hash', 'Hash' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "size" = ${Size}
            "filepath" = ${Filepath}
            "hash" = ${Hash}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to EcuInfoImage<PSCustomObject>

.DESCRIPTION

Convert from JSON to EcuInfoImage<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

EcuInfoImage<PSCustomObject>
#>
function ConvertFrom-TorizonPlatformAPIJsonToEcuInfoImage {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIEcuInfoImage' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TorizonPlatformAPIEcuInfoImage
        $AllProperties = ("size", "filepath", "hash")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'size' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "size"))) {
            throw "Error! JSON cannot be serialized due to the required property 'size' missing."
        } else {
            $Size = $JsonParameters.PSobject.Properties["size"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "filepath"))) {
            throw "Error! JSON cannot be serialized due to the required property 'filepath' missing."
        } else {
            $Filepath = $JsonParameters.PSobject.Properties["filepath"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hash"))) {
            throw "Error! JSON cannot be serialized due to the required property 'hash' missing."
        } else {
            $Hash = $JsonParameters.PSobject.Properties["hash"].value
        }

        $PSO = [PSCustomObject]@{
            "size" = ${Size}
            "filepath" = ${Filepath}
            "hash" = ${Hash}
        }

        return $PSO
    }

}

