#
# Torizon OTA
#  This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  
# Version: 2.0-Beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Comment
No description available.
.PARAMETER ProprietaryMeta
No description available.
.PARAMETER Uri
No description available.
.PARAMETER HardwareIds
No description available.
.OUTPUTS

EditPackage<PSCustomObject>
#>

function Initialize-TorizonPlatformAPIEditPackage {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Comment},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProprietaryMeta},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Uri},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${HardwareIds}
    )

    Process {
        'Creating PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIEditPackage' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "comment" = ${Comment}
            "proprietaryMeta" = ${ProprietaryMeta}
            "uri" = ${Uri}
            "hardwareIds" = ${HardwareIds}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to EditPackage<PSCustomObject>

.DESCRIPTION

Convert from JSON to EditPackage<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

EditPackage<PSCustomObject>
#>
function ConvertFrom-TorizonPlatformAPIJsonToEditPackage {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIEditPackage' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TorizonPlatformAPIEditPackage
        $AllProperties = ("comment", "proprietaryMeta", "uri", "hardwareIds")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "comment"))) { #optional property not found
            $Comment = $null
        } else {
            $Comment = $JsonParameters.PSobject.Properties["comment"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "proprietaryMeta"))) { #optional property not found
            $ProprietaryMeta = $null
        } else {
            $ProprietaryMeta = $JsonParameters.PSobject.Properties["proprietaryMeta"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "uri"))) { #optional property not found
            $Uri = $null
        } else {
            $Uri = $JsonParameters.PSobject.Properties["uri"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hardwareIds"))) { #optional property not found
            $HardwareIds = $null
        } else {
            $HardwareIds = $JsonParameters.PSobject.Properties["hardwareIds"].value
        }

        $PSO = [PSCustomObject]@{
            "comment" = ${Comment}
            "proprietaryMeta" = ${ProprietaryMeta}
            "uri" = ${Uri}
            "hardwareIds" = ${HardwareIds}
        }

        return $PSO
    }

}

