#
# Torizon OTA
#  This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  
# Version: 2.0-Beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Hashes
No description available.
.PARAMETER Length
No description available.
.OUTPUTS

FileInfo<PSCustomObject>
#>

function Initialize-TorizonPlatformAPIFileInfo {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Hashes},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int64]
        ${Length}
    )

    Process {
        'Creating PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIFileInfo' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Hashes) {
            throw "invalid value for 'Hashes', 'Hashes' cannot be null."
        }

        if ($null -eq $Length) {
            throw "invalid value for 'Length', 'Length' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "hashes" = ${Hashes}
            "length" = ${Length}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to FileInfo<PSCustomObject>

.DESCRIPTION

Convert from JSON to FileInfo<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

FileInfo<PSCustomObject>
#>
function ConvertFrom-TorizonPlatformAPIJsonToFileInfo {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIFileInfo' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TorizonPlatformAPIFileInfo
        $AllProperties = ("hashes", "length")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'hashes' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hashes"))) {
            throw "Error! JSON cannot be serialized due to the required property 'hashes' missing."
        } else {
            $Hashes = $JsonParameters.PSobject.Properties["hashes"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "length"))) {
            throw "Error! JSON cannot be serialized due to the required property 'length' missing."
        } else {
            $Length = $JsonParameters.PSobject.Properties["length"].value
        }

        $PSO = [PSCustomObject]@{
            "hashes" = ${Hashes}
            "length" = ${Length}
        }

        return $PSO
    }

}

