#
# Torizon OTA
#  This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  
# Version: 2.0-Beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Installed
No description available.
.PARAMETER Component
No description available.
.OUTPUTS

InstalledPackage<PSCustomObject>
#>

function Initialize-TorizonPlatformAPIInstalledPackage {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Installed},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Component}
    )

    Process {
        'Creating PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIInstalledPackage' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Installed) {
            throw "invalid value for 'Installed', 'Installed' cannot be null."
        }

        if ($null -eq $Component) {
            throw "invalid value for 'Component', 'Component' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "installed" = ${Installed}
            "component" = ${Component}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to InstalledPackage<PSCustomObject>

.DESCRIPTION

Convert from JSON to InstalledPackage<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

InstalledPackage<PSCustomObject>
#>
function ConvertFrom-TorizonPlatformAPIJsonToInstalledPackage {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIInstalledPackage' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TorizonPlatformAPIInstalledPackage
        $AllProperties = ("installed", "component")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'installed' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "installed"))) {
            throw "Error! JSON cannot be serialized due to the required property 'installed' missing."
        } else {
            $Installed = $JsonParameters.PSobject.Properties["installed"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "component"))) {
            throw "Error! JSON cannot be serialized due to the required property 'component' missing."
        } else {
            $Component = $JsonParameters.PSobject.Properties["component"].value
        }

        $PSO = [PSCustomObject]@{
            "installed" = ${Installed}
            "component" = ${Component}
        }

        return $PSO
    }

}

