#
# Torizon OTA
#  This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  
# Version: 2.0-Beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Signatures
No description available.
.PARAMETER Signed
No description available.
.OUTPUTS

JsonSignedPayload<PSCustomObject>
#>

function Initialize-TorizonPlatformAPIJsonSignedPayload {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Signatures},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Signed}
    )

    Process {
        'Creating PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIJsonSignedPayload' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "signatures" = ${Signatures}
            "signed" = ${Signed}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to JsonSignedPayload<PSCustomObject>

.DESCRIPTION

Convert from JSON to JsonSignedPayload<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

JsonSignedPayload<PSCustomObject>
#>
function ConvertFrom-TorizonPlatformAPIJsonToJsonSignedPayload {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIJsonSignedPayload' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TorizonPlatformAPIJsonSignedPayload
        $AllProperties = ("signatures", "signed")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'signed' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "signed"))) {
            throw "Error! JSON cannot be serialized due to the required property 'signed' missing."
        } else {
            $Signed = $JsonParameters.PSobject.Properties["signed"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "signatures"))) { #optional property not found
            $Signatures = $null
        } else {
            $Signatures = $JsonParameters.PSobject.Properties["signatures"].value
        }

        $PSO = [PSCustomObject]@{
            "signatures" = ${Signatures}
            "signed" = ${Signed}
        }

        return $PSO
    }

}

