#
# Torizon OTA
#  This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  
# Version: 2.0-Beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER NotAffected
No description available.
.PARAMETER Affected
No description available.
.OUTPUTS

UpdateCreateResult<PSCustomObject>
#>

function Initialize-TorizonPlatformAPIUpdateCreateResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${NotAffected},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Affected}
    )

    Process {
        'Creating PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIUpdateCreateResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "notAffected" = ${NotAffected}
            "affected" = ${Affected}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to UpdateCreateResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to UpdateCreateResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

UpdateCreateResult<PSCustomObject>
#>
function ConvertFrom-TorizonPlatformAPIJsonToUpdateCreateResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: TorizonPlatformAPI => TorizonPlatformAPIUpdateCreateResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TorizonPlatformAPIUpdateCreateResult
        $AllProperties = ("notAffected", "affected")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "notAffected"))) { #optional property not found
            $NotAffected = $null
        } else {
            $NotAffected = $JsonParameters.PSobject.Properties["notAffected"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "affected"))) { #optional property not found
            $Affected = $null
        } else {
            $Affected = $JsonParameters.PSobject.Properties["affected"].value
        }

        $PSO = [PSCustomObject]@{
            "notAffected" = ${NotAffected}
            "affected" = ${Affected}
        }

        return $PSO
    }

}

